"""initial_setup

Revision ID: f6a934612611
Revises: 
Create Date: 2026-05-05 19:51:27.760625

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # This ensures SQLModel types work in every migration


# revision identifiers, used by Alembic.
revision = 'f6a934612611'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('card_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
